name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Deploy to Azure Static Web Apps
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_FLOWER_09040340F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Only needed for PRs; safe to include
          action: "upload"
          app_location: "/"            # Source folder
          output_location: "/"         # No build, just use root
          skip_app_build: true         # Tell Azure not to build
