name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v2
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_FLOWER_09040340F }}
          action: upload
          app_location: "./"           # Root of your repo where index.html lives
          skip_app_build: true        # IMPORTANT: prevents Azure from looking for package.json
