name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Static HTML Site
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_FLOWER_09040340F }}
          action: "upload"
          app_location: "/"        # Folder containing your index.html
          output_location: "/"     # Final site content lives here
          skip_app_build: true     # Skips all Node/NPM assumptions
